/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */
`include "cmos_cells.v"

(* top =  1  *)
(* src = "Byte_Striping.v:1" *)
module Byte_Striping(tx_data, tx_valid, clk, lane0, lane1, lane2, lane3, stripping_valid, counter, init);
  (* src = "Byte_Striping.v:22" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "Byte_Striping.v:5" *)
  input clk;
  (* src = "Byte_Striping.v:13" *)
  output [1:0] counter;
  (* src = "Byte_Striping.v:14" *)
  input init;
  (* src = "Byte_Striping.v:7" *)
  output [7:0] lane0;
  (* src = "Byte_Striping.v:8" *)
  output [7:0] lane1;
  (* src = "Byte_Striping.v:9" *)
  output [7:0] lane2;
  (* src = "Byte_Striping.v:10" *)
  output [7:0] lane3;
  (* src = "Byte_Striping.v:11" *)
  output stripping_valid;
  (* src = "Byte_Striping.v:3" *)
  input [7:0] tx_data;
  (* src = "Byte_Striping.v:4" *)
  input tx_valid;
  NOR _18_ (
    .A(tx_valid),
    .B(lane3[1]),
    .Y(_01_)
  );
  NOT _19_ (
    .A(tx_valid),
    .Y(_02_)
  );
  NOR _20_ (
    .A(_02_),
    .B(tx_data[1]),
    .Y(_03_)
  );
  NOR _21_ (
    .A(_03_),
    .B(_01_),
    .Y(_00_[1])
  );
  NOR _22_ (
    .A(lane3[2]),
    .B(tx_valid),
    .Y(_04_)
  );
  NOR _23_ (
    .A(tx_data[2]),
    .B(_02_),
    .Y(_05_)
  );
  NOR _24_ (
    .A(_05_),
    .B(_04_),
    .Y(_00_[2])
  );
  NOR _25_ (
    .A(lane3[3]),
    .B(tx_valid),
    .Y(_06_)
  );
  NOR _26_ (
    .A(tx_data[3]),
    .B(_02_),
    .Y(_07_)
  );
  NOR _27_ (
    .A(_07_),
    .B(_06_),
    .Y(_00_[3])
  );
  NOR _28_ (
    .A(lane3[4]),
    .B(tx_valid),
    .Y(_08_)
  );
  NOR _29_ (
    .A(tx_data[4]),
    .B(_02_),
    .Y(_09_)
  );
  NOR _30_ (
    .A(_09_),
    .B(_08_),
    .Y(_00_[4])
  );
  NOR _31_ (
    .A(lane3[5]),
    .B(tx_valid),
    .Y(_10_)
  );
  NOR _32_ (
    .A(tx_data[5]),
    .B(_02_),
    .Y(_11_)
  );
  NOR _33_ (
    .A(_11_),
    .B(_10_),
    .Y(_00_[5])
  );
  NOR _34_ (
    .A(lane3[6]),
    .B(tx_valid),
    .Y(_12_)
  );
  NOR _35_ (
    .A(tx_data[6]),
    .B(_02_),
    .Y(_13_)
  );
  NOR _36_ (
    .A(_13_),
    .B(_12_),
    .Y(_00_[6])
  );
  NOR _37_ (
    .A(lane3[7]),
    .B(tx_valid),
    .Y(_14_)
  );
  NOR _38_ (
    .A(tx_data[7]),
    .B(_02_),
    .Y(_15_)
  );
  NOR _39_ (
    .A(_15_),
    .B(_14_),
    .Y(_00_[7])
  );
  NOR _40_ (
    .A(lane3[0]),
    .B(tx_valid),
    .Y(_16_)
  );
  NOR _41_ (
    .A(tx_data[0]),
    .B(_02_),
    .Y(_17_)
  );
  NOR _42_ (
    .A(_17_),
    .B(_16_),
    .Y(_00_[0])
  );
  DFF _43_ (
    .C(clk),
    .D(_00_[0]),
    .Q(lane3[0])
  );
  DFF _44_ (
    .C(clk),
    .D(_00_[1]),
    .Q(lane3[1])
  );
  DFF _45_ (
    .C(clk),
    .D(_00_[2]),
    .Q(lane3[2])
  );
  DFF _46_ (
    .C(clk),
    .D(_00_[3]),
    .Q(lane3[3])
  );
  DFF _47_ (
    .C(clk),
    .D(_00_[4]),
    .Q(lane3[4])
  );
  DFF _48_ (
    .C(clk),
    .D(_00_[5]),
    .Q(lane3[5])
  );
  DFF _49_ (
    .C(clk),
    .D(_00_[6]),
    .Q(lane3[6])
  );
  DFF _50_ (
    .C(clk),
    .D(_00_[7]),
    .Q(lane3[7])
  );
  assign counter = 2'b11;
  assign stripping_valid = 1'b1;
endmodule
