/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "Byte_Striping.v:1" *)
module Byte_Striping(tx_data, tx_valid, clk, lane0, lane1, lane2, lane3, stripping_valid, counter, init);
  (* src = "Byte_Striping.v:22" *)
  wire [7:0] _00_;
  (* src = "Byte_Striping.v:5" *)
  input clk;
  (* src = "Byte_Striping.v:13" *)
  output [1:0] counter;
  (* src = "Byte_Striping.v:14" *)
  input init;
  (* src = "Byte_Striping.v:7" *)
  output [7:0] lane0;
  (* src = "Byte_Striping.v:8" *)
  output [7:0] lane1;
  (* src = "Byte_Striping.v:9" *)
  output [7:0] lane2;
  (* src = "Byte_Striping.v:10" *)
  output [7:0] lane3;
  reg [7:0] lane3;
  (* src = "Byte_Striping.v:11" *)
  output stripping_valid;
  (* src = "Byte_Striping.v:3" *)
  input [7:0] tx_data;
  (* src = "Byte_Striping.v:4" *)
  input tx_valid;
  assign _00_[0] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[0] : lane3[0];
  assign _00_[1] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[1] : lane3[1];
  assign _00_[2] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[2] : lane3[2];
  assign _00_[3] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[3] : lane3[3];
  assign _00_[4] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[4] : lane3[4];
  assign _00_[5] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[5] : lane3[5];
  assign _00_[6] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[6] : lane3[6];
  assign _00_[7] = tx_valid ? (* src = "Byte_Striping.v:44" *) tx_data[7] : lane3[7];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[0] <= _00_[0];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[1] <= _00_[1];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[2] <= _00_[2];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[3] <= _00_[3];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[4] <= _00_[4];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[5] <= _00_[5];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[6] <= _00_[6];
  (* src = "Byte_Striping.v:22" *)
  always @(posedge clk)
      lane3[7] <= _00_[7];
  assign counter = 2'b11;
  assign stripping_valid = 1'b1;
endmodule
