/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "mux.v:1" *)
module mux(clk, rst, enb, tx_Data, com, skp, stp, sdp, end_ok, edb, fts, idle, control_dk, tx_multiplexada, tx_Valid);
  (* src = "mux.v:38" *)
  wire _000_;
  (* src = "mux.v:38" *)
  wire [7:0] _001_;
  (* src = "mux.v:38" *)
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire [2:0] _034_;
  wire [1:0] _035_;
  wire [1:0] _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire [1:0] _039_;
  wire [1:0] _040_;
  wire [3:0] _041_;
  wire [1:0] _042_;
  wire _043_;
  wire [3:0] _044_;
  wire [1:0] _045_;
  wire _046_;
  wire [3:0] _047_;
  wire [1:0] _048_;
  wire _049_;
  wire [3:0] _050_;
  wire [1:0] _051_;
  wire _052_;
  wire [3:0] _053_;
  wire [1:0] _054_;
  wire _055_;
  wire [3:0] _056_;
  wire [1:0] _057_;
  wire _058_;
  wire [3:0] _059_;
  wire [1:0] _060_;
  wire _061_;
  wire [3:0] _062_;
  wire [1:0] _063_;
  wire _064_;
  wire [3:0] _065_;
  wire [1:0] _066_;
  wire _067_;
  wire [3:0] _068_;
  wire [3:0] _069_;
  (* src = "mux.v:41" *)
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* src = "mux.v:42|<techmap.v>:432" *)
  wire [71:0] _080_;
  (* src = "mux.v:42|<techmap.v>:428" *)
  wire [7:0] _081_;
  (* src = "mux.v:42|<techmap.v>:445" *)
  wire _082_;
  (* src = "mux.v:19" *)
  input clk;
  (* src = "mux.v:23" *)
  input [7:0] com;
  (* src = "mux.v:31" *)
  input [3:0] control_dk;
  (* src = "mux.v:28" *)
  input [7:0] edb;
  (* src = "mux.v:21" *)
  input enb;
  (* src = "mux.v:27" *)
  input [7:0] end_ok;
  (* src = "mux.v:29" *)
  input [7:0] fts;
  (* src = "mux.v:30" *)
  input [7:0] idle;
  (* src = "mux.v:20" *)
  input rst;
  (* src = "mux.v:26" *)
  input [7:0] sdp;
  (* src = "mux.v:24" *)
  input [7:0] skp;
  (* src = "mux.v:25" *)
  input [7:0] stp;
  (* src = "mux.v:22" *)
  input [7:0] tx_Data;
  (* src = "mux.v:33" *)
  output tx_Valid;
  (* src = "mux.v:32" *)
  output [7:0] tx_multiplexada;
  assign _034_[0] = _079_ | _078_;
  assign _035_[0] = _034_[0] | _034_[1];
  assign _035_[1] = _034_[2] | _071_;
  assign _003_ = _035_[0] | _035_[1];
  assign _007_ = _036_[0] |(* src = "mux.v:42" *)  _036_[1];
  assign _006_ = _037_[0] |(* src = "mux.v:42" *)  _037_[1];
  assign _037_[1] = _069_[2] |(* src = "mux.v:42" *)  _068_[3];
  assign _005_ = _038_[0] |(* src = "mux.v:42" *)  _037_[1];
  assign _004_ = _039_[0] |(* src = "mux.v:42" *)  _039_[1];
  assign _039_[1] = _069_[2] |(* src = "mux.v:42" *)  control_dk[3];
  assign _016_ = _036_[0] |(* src = "mux.v:42" *)  _039_[1];
  assign _037_[0] = _069_[0] |(* src = "mux.v:42" *)  _069_[1];
  assign _015_ = _037_[0] |(* src = "mux.v:42" *)  _036_[1];
  assign _038_[0] = control_dk[0] |(* src = "mux.v:42" *)  _069_[1];
  assign _036_[1] = control_dk[2] |(* src = "mux.v:42" *)  _068_[3];
  assign _014_ = _038_[0] |(* src = "mux.v:42" *)  _036_[1];
  assign _039_[0] = _069_[0] |(* src = "mux.v:42" *)  control_dk[1];
  assign _013_ = _039_[0] |(* src = "mux.v:42" *)  _040_[1];
  assign _027_ = _032_ | _010_;
  assign _029_ = rst | _033_;
  assign _041_[0] = _080_[6] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[14];
  assign _041_[1] = _080_[22] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[30];
  assign _041_[2] = _080_[38] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[46];
  assign _041_[3] = _080_[54] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[62];
  assign _042_[0] = _041_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _041_[1];
  assign _042_[1] = _041_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _041_[3];
  assign _043_ = _042_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _042_[1];
  assign _081_[6] = _043_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[70];
  assign _044_[0] = _080_[7] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[15];
  assign _044_[1] = _080_[23] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[31];
  assign _044_[2] = _080_[39] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[47];
  assign _044_[3] = _080_[55] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[63];
  assign _045_[0] = _044_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _044_[1];
  assign _045_[1] = _044_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _044_[3];
  assign _046_ = _045_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _045_[1];
  assign _081_[7] = _046_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[71];
  assign _047_[0] = _080_[5] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[13];
  assign _047_[1] = _080_[21] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[29];
  assign _047_[2] = _080_[37] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[45];
  assign _047_[3] = _080_[53] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[61];
  assign _048_[0] = _047_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _047_[1];
  assign _048_[1] = _047_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _047_[3];
  assign _049_ = _048_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _048_[1];
  assign _081_[5] = _049_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[69];
  assign _050_[0] = _080_[4] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[12];
  assign _050_[1] = _080_[20] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[28];
  assign _050_[2] = _080_[36] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[44];
  assign _050_[3] = _080_[52] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[60];
  assign _051_[0] = _050_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _050_[1];
  assign _051_[1] = _050_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _050_[3];
  assign _052_ = _051_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _051_[1];
  assign _081_[4] = _052_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[68];
  assign _053_[0] = _080_[3] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[11];
  assign _053_[1] = _080_[19] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[27];
  assign _053_[2] = _080_[35] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[43];
  assign _053_[3] = _080_[51] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[59];
  assign _054_[0] = _053_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _053_[1];
  assign _054_[1] = _053_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _053_[3];
  assign _055_ = _054_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _054_[1];
  assign _081_[3] = _055_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[67];
  assign _056_[0] = _080_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[10];
  assign _056_[1] = _080_[18] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[26];
  assign _056_[2] = _080_[34] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[42];
  assign _056_[3] = _080_[50] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[58];
  assign _057_[0] = _056_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _056_[1];
  assign _057_[1] = _056_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _056_[3];
  assign _058_ = _057_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _057_[1];
  assign _081_[2] = _058_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[66];
  assign _059_[0] = _080_[1] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[9];
  assign _059_[1] = _080_[17] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[25];
  assign _059_[2] = _080_[33] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[41];
  assign _059_[3] = _080_[49] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[57];
  assign _060_[0] = _059_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _059_[1];
  assign _060_[1] = _059_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _059_[3];
  assign _061_ = _060_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _060_[1];
  assign _081_[1] = _061_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[65];
  assign _062_[0] = _080_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[8];
  assign _062_[1] = _080_[16] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[24];
  assign _062_[2] = _080_[32] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[40];
  assign _062_[3] = _080_[48] |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[56];
  assign _063_[0] = _062_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _062_[1];
  assign _063_[1] = _062_[2] |(* src = "mux.v:42|<techmap.v>:441" *)  _062_[3];
  assign _064_ = _063_[0] |(* src = "mux.v:42|<techmap.v>:441" *)  _063_[1];
  assign _081_[0] = _064_ |(* src = "mux.v:42|<techmap.v>:441" *)  _080_[64];
  assign _065_[0] = _077_ |(* src = "mux.v:42|<techmap.v>:445" *)  _078_;
  assign _065_[1] = _079_ |(* src = "mux.v:42|<techmap.v>:445" *)  _071_;
  assign _034_[2] = _072_ |(* src = "mux.v:42|<techmap.v>:445" *)  _073_;
  assign _034_[1] = _074_ |(* src = "mux.v:42|<techmap.v>:445" *)  _075_;
  assign _066_[0] = _065_[0] |(* src = "mux.v:42|<techmap.v>:445" *)  _065_[1];
  assign _066_[1] = _034_[2] |(* src = "mux.v:42|<techmap.v>:445" *)  _034_[1];
  assign _067_ = _066_[0] |(* src = "mux.v:42|<techmap.v>:445" *)  _066_[1];
  assign _082_ = _067_ |(* src = "mux.v:42|<techmap.v>:445" *)  _076_;
  assign _036_[0] = control_dk[0] |(* src = "mux.v:42" *)  control_dk[1];
  assign _040_[1] = control_dk[2] |(* src = "mux.v:42" *)  control_dk[3];
  assign _012_ = _036_[0] |(* src = "mux.v:42" *)  _040_[1];
  assign _077_ = ~(* src = "mux.v:42" *) _007_;
  assign _078_ = ~(* src = "mux.v:42" *) _006_;
  assign _079_ = ~(* src = "mux.v:42" *) _005_;
  assign _071_ = ~(* src = "mux.v:42" *) _004_;
  assign _072_ = ~(* src = "mux.v:42" *) _016_;
  assign _073_ = ~(* src = "mux.v:42" *) _015_;
  assign _074_ = ~(* src = "mux.v:42" *) _014_;
  assign _075_ = ~(* src = "mux.v:42" *) _013_;
  assign _076_ = ~(* src = "mux.v:42" *) _012_;
  assign _070_ = _009_ &(* src = "mux.v:41" *)  enb;
  assign _000_ = ~(* src = "mux.v:42" *) _003_;
  assign _001_[0] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[0];
  assign _001_[1] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[1];
  assign _001_[2] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[2];
  assign _001_[3] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[3];
  assign _001_[4] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[4];
  assign _001_[5] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[5];
  assign _001_[6] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[6];
  assign _001_[7] = rst ? (* src = "mux.v:39" *) 1'b0 : _002_[7];
  assign _002_[0] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[0] : 1'b0;
  assign _002_[1] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[1] : 1'b0;
  assign _002_[2] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[2] : 1'b0;
  assign _002_[3] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[3] : 1'b0;
  assign _002_[4] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[4] : 1'b0;
  assign _002_[5] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[5] : 1'b0;
  assign _002_[6] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[6] : 1'b0;
  assign _002_[7] = _082_ ? (* src = "mux.v:42|<techmap.v>:445" *) _081_[7] : 1'b0;
  assign _010_ = ~_070_;
  assign _011_ = ~_031_;
  assign _009_ = ~rst;
  assign _008_ = ~_029_;
  \$_DLATCH_P_  _209_ (
    .D(_001_[0]),
    .E(_011_),
    .Q(tx_multiplexada[0])
  );
  \$_DLATCH_P_  _210_ (
    .D(_001_[1]),
    .E(_011_),
    .Q(tx_multiplexada[1])
  );
  \$_DLATCH_P_  _211_ (
    .D(_001_[2]),
    .E(_011_),
    .Q(tx_multiplexada[2])
  );
  \$_DLATCH_P_  _212_ (
    .D(_001_[3]),
    .E(_011_),
    .Q(tx_multiplexada[3])
  );
  \$_DLATCH_P_  _213_ (
    .D(_001_[4]),
    .E(_011_),
    .Q(tx_multiplexada[4])
  );
  \$_DLATCH_P_  _214_ (
    .D(_001_[5]),
    .E(_011_),
    .Q(tx_multiplexada[5])
  );
  \$_DLATCH_P_  _215_ (
    .D(_001_[6]),
    .E(_011_),
    .Q(tx_multiplexada[6])
  );
  \$_DLATCH_P_  _216_ (
    .D(_001_[7]),
    .E(_011_),
    .Q(tx_multiplexada[7])
  );
  \$_DLATCH_P_  _217_ (
    .D(_000_),
    .E(_008_),
    .Q(tx_Valid)
  );
  assign _069_[2] = control_dk[2] ^(* src = "mux.v:42" *)  1'b1;
  assign _069_[1] = control_dk[1] ^(* src = "mux.v:42" *)  1'b1;
  assign _068_[3] = control_dk[3] ^(* src = "mux.v:42" *)  1'b1;
  assign _069_[0] = control_dk[0] ^(* src = "mux.v:42" *)  1'b1;
  assign _030_ = _009_ & _010_;
  assign _031_ = _009_ & _030_;
  assign _017_ = _006_ & _007_;
  assign _018_ = _005_ & _017_;
  assign _019_ = _004_ & _018_;
  assign _020_ = _016_ & _019_;
  assign _021_ = _015_ & _020_;
  assign _022_ = _014_ & _021_;
  assign _023_ = _013_ & _022_;
  assign _024_ = _012_ & _023_;
  assign _025_ = _070_ & _024_;
  assign _026_ = _009_ & _025_;
  assign _032_ = _070_ & _026_;
  assign _028_ = _009_ & _027_;
  assign _033_ = _009_ & _028_;
  assign _080_[64] = tx_Data[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[65] = tx_Data[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[66] = tx_Data[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[67] = tx_Data[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[68] = tx_Data[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[69] = tx_Data[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[70] = tx_Data[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[71] = tx_Data[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _076_;
  assign _080_[56] = com[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[57] = com[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[58] = com[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[59] = com[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[60] = com[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[61] = com[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[62] = com[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[63] = com[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _075_;
  assign _080_[48] = skp[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[49] = skp[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[50] = skp[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[51] = skp[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[52] = skp[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[53] = skp[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[54] = skp[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[55] = skp[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _074_;
  assign _080_[40] = stp[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[41] = stp[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[42] = stp[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[43] = stp[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[44] = stp[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[45] = stp[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[46] = stp[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[47] = stp[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _073_;
  assign _080_[32] = sdp[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[33] = sdp[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[34] = sdp[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[35] = sdp[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[36] = sdp[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[37] = sdp[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[38] = sdp[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[39] = sdp[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _072_;
  assign _080_[24] = end_ok[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[25] = end_ok[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[26] = end_ok[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[27] = end_ok[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[28] = end_ok[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[29] = end_ok[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[30] = end_ok[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[31] = end_ok[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _071_;
  assign _080_[16] = edb[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[17] = edb[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[18] = edb[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[19] = edb[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[20] = edb[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[21] = edb[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[22] = edb[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[23] = edb[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _079_;
  assign _080_[8] = fts[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[9] = fts[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[10] = fts[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[11] = fts[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[12] = fts[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[13] = fts[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[14] = fts[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[15] = fts[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _078_;
  assign _080_[0] = idle[0] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[1] = idle[1] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[2] = idle[2] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[3] = idle[3] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[4] = idle[4] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[5] = idle[5] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[6] = idle[6] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
  assign _080_[7] = idle[7] &(* src = "mux.v:42|<techmap.v>:434" *)  _077_;
endmodule
